### PR TITLE
Add new directions

### PR DESCRIPTION
**Pull request by droid-kk11**
This would add more directions for more precise control.

**Specifics**
Added directions:

- UPLEFT (315 deg)
- LEFTDOWN (225 deg)
- RIGHTDOWN (135 deg)
- UPRIGHT (45 deg)

Please feel free to make minor changes as needed.

### CODE REVIEW

**Review by philiparola — CHANGES_REQUESTED** [review]
1) This code looks like it wont compile since you didn't add the directions to the class enum on line 110
2) What's the point of this code?  This whole dataset seems to be unused.  The general etiquette of Pull Requests is that there is some new functionality or a patch introduced; something substantial

**Comment by droid-kk11** [comment]
Ok, will make the changes. The point of this PR was to make the controls more precise. Will make some changes.

**Comment by philiparola** [comment]
It looks like these changes are a duplicate of 15ad436df611687ca9c28ce728586fb62d69ce1e which also implements them fully.  Closing this

**Comment by droid-kk11** [comment]
Well, technically, Grant implemented my changes in his PR, but sure, close this one.-KSSent from my iPhoneOn Feb 12, 2024, at 18:16, Philip Arola ***@***.***> wrote:﻿
It looks like these changes are a duplicate of 15ad436 which also implements them fully.  Closing this

**Pull request closed without merging**
